AssignToMonth/Controllers/AllocateTimesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssignToMonth.Data;
using AssignToMonth.Models;
using AssignToMonth.ViewModels;
using X.PagedList;

namespace AssignToMonth.Controllers
{
    public class AllocateTimesController : Controller
    {
        private readonly SqlDbContext _context;

        public AllocateTimesController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: AllocateTimes
        public IActionResult Index(int? year, string month, string customer, int? page, int currentYear, string currentMonth, string currentCustomer)
        {
            ViewBag.Year = (from item in _context.Months
                            orderby item.Year
                            select item.Year).Distinct();
            ViewBag.Month = (from item in _context.Months
                             orderby item.Id
                             select item.MonthName).Distinct();
            ViewBag.Customers = (from item in _context.Customers
                                 orderby item.Id
                                 select item.Name).Distinct();

            if (year != null || month != null || customer != null)
            {
                page = 1;
            }
            else
            {
                year = currentYear;
                customer = currentCustomer;
                month = currentMonth;
            }

            ViewBag.CurrentCustomer = customer;
            ViewBag.CurrentYear = year;
            ViewBag.CurrentMonth = month;

            int pageNumber = page ?? 1;
            int pageSize = 12;

            var viewModel = new AllocateTimeViewModel()
            {
                GetAllCustomers = from item in _context.AssignCustomerToMonths.Include(c => c.Customer)
                                            .Include(m => m.Month)
                                                .Include(a => a.AllocateTimes)
                                  orderby item.Month.Id
                                  where item.Month.Year == year || year == null || year == 0
                                  where item.Month.MonthName == month || month == null || month == ""
                                  where item.Customer.Name == customer || customer == null || customer == ""
                                  select item,

                AllocateTimes = (from item in _context.AllocateTime
                                       .Include(u => u.User.User)
                                         .Include(u => u.Customer.Customer)
                                             .Include(u => u.User.Month)
                                 orderby item.User.Month.Id
                                 where item.User.Month.Year == year || year == null || year == 0
                                 where item.User.Month.MonthName == month || month == null || month == ""
                                 where item.Customer.Customer.Name == customer || customer == null || customer == ""
                                 select item).ToPagedList(pageNumber, pageSize),   
            };

            return View(viewModel);
        }

        #region CREATE METHOD
        // GET: AllocateTimes/Create
        public IActionResult Create()
        {
            ViewBag.Customer = new SelectList(_context.AssignCustomerToMonths, "Id", "CustomerId");
            ViewBag.User = new SelectList(_context.AssignedMonths, "Id", "UserId");
            return View();
        }

        // POST: AllocateTimes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AllocateTime allocateTime)
        {
            ViewBag.Customer = new SelectList(_context.AssignCustomerToMonths, "Id", "CustomerId");
            ViewBag.User = new SelectList(_context.AssignedMonths, "Id", "UserId");

            if (ModelState.IsValid)
            {
                _context.Add(allocateTime);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(allocateTime);
        }

        #endregion

        #region EDIT METHOD
        // GET: AllocateTimes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var allocateTime = await _context.AllocateTime.FindAsync(id);
            if (allocateTime == null)
            {
                return NotFound();
            }
            return View(allocateTime);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUser(AllocateTime _user)
        {
            var months = await _context.Months.ToListAsync();

            //Hämta användarens totala arbetstid som ska planeras ut per månad
            var getUser = await _context.AssignedMonths.FindAsync(_user.UserId);
            var userTotalHours = getUser.TotalHours();

            //Hämta användarens aktuella utplanerade tid per månad
            var getUserTime = await _context.AllocateTime.FindAsync(_user.Id);
            var userTime = getUserTime.AllocatedHours;

            //Hämta användarens tid utplanerad på alla kunder per månad
            var getUserSumHours = _context.AllocateTime.Where(u => u.UserId == _user.UserId).Select(x => x.AllocatedHours);
            var userSumHours = getUserSumHours.Sum();


            //Hämta kundens totala FTE som ska planeras ut per månad
            var getCustomer = await _context.AssignCustomerToMonths.FindAsync(_user.CustomerId);
            var customerTotalHours = getCustomer.FteToHours();

            //Hämta kundens aktuella utplanerade tid per månad
            var getCustomerTime = await _context.AllocateTime.FindAsync(_user.Id);
            var customerTime = getCustomerTime.AllocatedHours;

            //Hämta kundens tid utplanerad på alla användare per månad
            var getCustomerAllHours = _context.AllocateTime.Where(u => u.CustomerId == _user.CustomerId).Select(x => x.AllocatedHours);
            var customerSumHours = getCustomerAllHours.Sum();

            //Beräkning av nuvarande planerad tid mot ny planerad tid
            var userTimeDiff = userSumHours - userTime + _user.AllocatedHours;
            var customerTimeDiff = customerSumHours - customerTime + _user.AllocatedHours;

            var updatedUser = await _context.AllocateTime.Where(x => x.Id == _user.Id).SingleOrDefaultAsync();

            if (updatedUser != null)
            {
                if (userTimeDiff <= userTotalHours && customerTimeDiff <= customerTotalHours)
                {
                    updatedUser.AllocatedHours = _user.AllocatedHours;
                    await _context.SaveChangesAsync();
                }
                else if (userTimeDiff > userTotalHours)
                {
                    TempData["UserError"] = "Du kan inte planera ut mer tid på denna användare";
                }
                else if (customerTimeDiff > customerTotalHours)
                {
                    TempData["CustomerError"] = "Du kan inte planera ut mer tid på denna kund";
                }
            }
            return new EmptyResult();
        }
        #endregion

        #region DELETE METHOD
        // GET: AllocateTimes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var allocateTime = await _context.AllocateTime
                .FirstOrDefaultAsync(m => m.Id == id);
            if (allocateTime == null)
            {
                return NotFound();
            }

            return View(allocateTime);
        }

        // POST: AllocateTimes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var allocateTime = await _context.AllocateTime.FindAsync(id);
            _context.AllocateTime.Remove(allocateTime);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        private bool AllocateTimeExists(int id)
        {
            return _context.AllocateTime.Any(e => e.Id == id);
        }
                
    }
}

AssignToMonth/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssignToMonth.Data;
using AssignToMonth.Models;

namespace AssignToMonth.Controllers
{
    public class CustomersController : Controller
    {
        private readonly SqlDbContext _context;

        public CustomersController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.ToListAsync());
        }

        #region CREATE METHOD

        // GET: Customers/Create
        public IActionResult Create()
        {
            List<Customer> customers = new List<Customer> { new Customer { Id = 0, Name = "" } };
            return View(customers);
        }


        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(List<Customer> customers)
        {
            if (ModelState.IsValid)
            {
                foreach (var customer in customers)
                {
                    _context.Customers.Add(customer);
                    await _context.SaveChangesAsync();

                    foreach (var month in _context.Months)
                    {
                        AssignCustomerToMonth model = new AssignCustomerToMonth();
                        model.CustomerId = customer.Id;
                        for (int i = 0; i < month.Id; i++)
                        {
                            model.MonthId = month.Id;
                        }
                        model.FTE = 0;
                        _context.AssignCustomerToMonths.Add(model);
                    }
                }
                await _context.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            return View(customers);
        }

        #endregion

        #region EDIT METHOD
        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        #endregion

        #region DELETE METHOD

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }

        #endregion
    }
}

AssignToMonth/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssignToMonth.Data;
using AssignToMonth.Models;

namespace AssignToMonth.Controllers
{
    public class UsersController : Controller
    {
        private readonly SqlDbContext _context;

        public UsersController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public IActionResult Index()
        {
            var usersToEdit = from item in _context.Users
                              orderby item.Id
                              select item;         

            return View(usersToEdit.ToList());            
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            List<User> user = new List<User> { new User { Id = 0, FirstName = "", LastName = "" } };
            return View(user);
        }

        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(List<User> users)
        {
            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    _context.Users.Add(user);
                    await _context.SaveChangesAsync();

                    foreach (var month in _context.Months)
                    {
                        AssignedMonth model = new AssignedMonth();
                        model.UserId = user.Id;
                        for (int i = 0; i < month.Id; i++)
                        {
                            model.MonthId = month.Id;
                        }
                        model.Absence = 0;
                        _context.AssignedMonths.Add(model);
                    }
                }
                await _context.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateUser(User user)
        {
            User updatedUser = (from u in _context.Users
                                where u.Id == user.Id
                                select u).FirstOrDefault();

            updatedUser.FirstName = user.FirstName;
            updatedUser.LastName = user.LastName;
            await _context.SaveChangesAsync();

            return new EmptyResult();
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

AssignToMonth/Views/Dashboard/Index.cshtml
@model DashboardViewModel

@{
    ViewData["Title"] = "Dashboard";
}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <a asp-action="Index" asp-controller="AllocateTimes">
                <div class="card-counter danger">
                    <i class="fas fa-hourglass-start"></i>
                    <span class="count-name">Planera</span>
                </div>
            </a>
        </div>

        <div class="col-md-4">
            <a asp-action="Index" asp-controller="Customers">
                <div class="card-counter success">
                    <i class="fas fa-user-tie"></i>
                    <span class="count-numbers">@Model.TotalProjects</span>
                    <span class="count-name">Kunder</span>
                </div>
            </a>
        </div>

        <div class="col-md-4">
            <a asp-action="Index" asp-controller="Users">
                <div class="card-counter info">
                    <i class="fa fa-users"></i>
                    <span class="count-numbers">@Model.TotalUsers</span>
                    <span class="count-name">Användare</span>
                </div>
            </a>
        </div>
    </div>
</div>

<p>
    @using (Html.BeginForm("Index", "Dashboard", FormMethod.Get))
    {
    <div class="col-2 p-0">
        <span>År</span>@Html.DropDownList("year", new SelectList(ViewBag.Year), "Välj år", new { @class = "form-control" })
        <span>Månad</span>@Html.DropDownList("month", new SelectList(ViewBag.Month), "Välj månad", new { @class = "form-control" })
        <div id="userBtn" class="d-flex justify-content-between">
            <input class="btn btn-dark mt-3 col-5" type="submit" value="Sök" />
            <a class="btn btn-dark mt-3 col-5" asp-action="Index">Rensa</a>
        </div>
        
    </div>

    }
</p>
<div class="dashboard-overview mt-2">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link active rounded-0" data-toggle="pill" href="#home">Användare</a>
        </li>
        <li class="nav-item">
            <a class="nav-link rounded-0" data-toggle="pill" href="#menu1">Kunder</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane container active p-0" id="home">
            <h5 class="text-uppercase p-2 text-center">Användare</h5>
            <table class="table styled-table-users">
                <thead class="text-white" style="background-color: #26c6da;">
                    <tr>
                        <th>@Html.DisplayNameFor(m => Model.AssignedUsersToMonths.FirstOrDefault().Month.DisplayMonth)</th>
                        <th>@Html.DisplayNameFor(m => Model.Users.FirstOrDefault().DisplayName)</th>
                        <th>Månad (h)</th>
                        <th>@Html.DisplayNameFor(m => Model.AssignedUsersToMonths.FirstOrDefault().Absence)<span> (h)</span></th>
                        <th>Total tid (h)</th>
                        <th>Allokerad tid</th>
                        <th>Tid kvar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.AssignedUsersToMonths)
                    {
                        <tr class="userInfo">
                            <td>@user.Month.DisplayMonth </td>
                            <td>@user.User.DisplayName</td>
                            <td>@user.Month.Hours</td>
                            <td>@user.Absence</td>
                            <td class="totalHours">
                                @String.Format(("{0:n0}"), user.TotalHours())
                            </td>
                            <td class="assignedHours">
                                @{
                                    int sum = 0;
                                    @foreach (var hours in user.AllocateTimes)
                                    {
                                        sum += Convert.ToInt32(hours.AllocatedHours);
                                    }
                                    @Html.DisplayTextFor(m => sum)
                                }
                            </td>
                            <td class="hoursLeft">
                                @{
                                    var value = (user.TotalHours() - sum);
                                    var displayValue = String.Format("{0:N0}", value);
                                    @Html.DisplayTextFor(m => displayValue);
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="col-12 align-content-center">
                Sida @(Model.AssignedUsersToMonths.PageCount < Model.AssignedUsersToMonths.PageNumber ? 0 : Model.AssignedUsersToMonths.PageNumber) av @Model.AssignedUsersToMonths.PageCount
                @Html.PagedListPager(Model.AssignedUsersToMonths, page => Url.Action("Index", new { page, currentYear = ViewBag.CurrentYear, currentMonth = ViewBag.CurrentMonth, }), new X.PagedList.Web.Common.PagedListRenderOptions
                {
                    ContainerDivClasses = new[] { "navigation" },
                    LiElementClasses = new[] { "page-item" },
                    PageClasses = new[] { "page-link" },
                })
            </div>
        </div>
        <div class="tab-pane container fade p-0" id="menu1">
            <h5 class="text-uppercase p-2 text-center">Kunder</h5>
            <table class="table styled-table-customers">
                <thead class="text-white" style="background-color:#66bb6a;">
                    <tr>
                        <th>@Html.DisplayNameFor(m => Model.AssignedCustomerToMonths.FirstOrDefault().Month.DisplayMonth)</th>
                        <th>@Html.DisplayNameFor(m => Model.AssignedCustomerToMonths.FirstOrDefault().Customer.Name)</th>
                        <th>@Html.DisplayNameFor(m => Model.AssignedCustomerToMonths.FirstOrDefault().FTE)</th>
                        <th>Totalt (h)</th>
                        <th>Allokerad tid</th>
                        <th>Tid kvar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var customer in Model.AssignedCustomerToMonths)
                    {
                        <tr>
                            <td>@customer.Month.DisplayMonth</td>
                            <td>@customer.Customer.Name</td>
                            <td>@customer.FTE</td>
                            <td>@customer.FteToHours()</td>
                            <td>
                                @{
                                    int sum = 0;

                                    if (customer.AllocateTimes == null)
                                    {

                                    }
                                    else
                                    {
                                        foreach (var hours in customer.AllocateTimes)
                                        {

                                            sum += Convert.ToInt32(hours.AllocatedHours);
                                        }

                                        @Html.DisplayTextFor(m => sum)
                                    }

                                }
                            </td>
                            <td>
                                @{
                                    var value = (customer.FteToHours() - sum);
                                    var displayValue = String.Format("{0:N0}", value);
                                    @Html.DisplayTextFor(m => displayValue);
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="col-12 align-content-center">
                Sida @(Model.AssignedCustomerToMonths.PageCount < Model.AssignedCustomerToMonths.PageNumber ? 0 : Model.AssignedCustomerToMonths.PageNumber) av @Model.AssignedCustomerToMonths.PageCount
                @Html.PagedListPager(Model.AssignedCustomerToMonths, page => Url.Action("Index", new { page }), new X.PagedList.Web.Common.PagedListRenderOptions
                {
                    ContainerDivClasses = new[] { "navigation" },
                    LiElementClasses = new[] { "page-item" },
                    PageClasses = new[] { "page-link" },
                })
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>
    <script type="text/javascript">

    </script>
}