AssignToMonth/Controllers/AssignedCustomerToMonthsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssignToMonth.Data;
using AssignToMonth.Models;
using X.PagedList;
using Newtonsoft.Json;

namespace AssignToMonth.Controllers
{
    public class AssignedCustomerToMonthsController : Controller
    {
        private readonly SqlDbContext _context;

        public AssignedCustomerToMonthsController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: AssignCustomerToMonths
        public IActionResult Index(int? year, string month, int? page, int currentYear, string currentMonth)
        {
            ViewBag.Year = (from item in _context.Months
                            orderby item.Year
                            select item.Year).Distinct();
            ViewBag.Month = (from item in _context.Months
                             orderby item.Id
                             select item.MonthName).Distinct();

            if (year != null || month != null)
            {
                page = 1;
            }
            else
            {
                year = currentYear;
                month = currentMonth;
            }

            ViewBag.CurrentYear = year;
            ViewBag.CurrentMonth = month;

            var pageNumber = page ?? 1;
            int pageSize = 12;

            var model = from item in _context.AssignCustomerToMonths
                            .Include(a => a.Customer)
                                .Include(a => a.Month)
                        orderby item.Month.Id   
                        where item.Month.Year == year || year == null || year == 0
                        where item.Month.MonthName == month || month == null || month ==""
                        select item;

            return View(model.ToPagedList(pageNumber, pageSize));
        }

        #region CREATE METHOD
        // GET: AssignCustomerToMonths/Create
        public IActionResult Create()
        {
            ViewBag.Customers = new SelectList(_context.Customers, "Id", "Name");
            ViewBag.Months = new SelectList(_context.Months, "Id", "DisplayMonth");

            List<AssignCustomerToMonth> assignedCustomers = new List<AssignCustomerToMonth> { new AssignCustomerToMonth { Id = 0, CustomerId = 0, MonthId = 0, FTE = 0} };
            return View(assignedCustomers);
        }

        // POST: AssignCustomerToMonths/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(List<AssignCustomerToMonth> assignCustomers)
        {
            ViewBag.Customers = new SelectList(_context.Customers, "Id", "Name");
            ViewBag.Months = new SelectList(_context.Months, "Id", "DisplayMonth");

            if (ModelState.IsValid)
            {
                foreach (var customer in assignCustomers)
                {
                    _context.Add(customer);
                }

                await _context.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            return View(assignCustomers);
        }
        #endregion

        #region EDIT METHOD
        // GET: AssignCustomerToMonths/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignCustomerToMonth = await _context.AssignCustomerToMonths.FindAsync(id);
            if (assignCustomerToMonth == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Name", assignCustomerToMonth.CustomerId);
            ViewData["MonthId"] = new SelectList(_context.Months, "Id", "DisplayMonth", assignCustomerToMonth.MonthId);
            return View(assignCustomerToMonth);
        }
        
        [HttpPost]
        public async Task<IActionResult> UpdateCustomer(AssignCustomerToMonth _customer)
        {

            var updatedCustomer = await _context.AssignCustomerToMonths.Where(x => x.Id == _customer.Id).SingleOrDefaultAsync();

            if (updatedCustomer != null)
            {
                updatedCustomer.FTE = _customer.FTE;
                await _context.SaveChangesAsync();
            }
            return new EmptyResult();
        }

        #endregion

        #region DELETE METHOD
        // GET: AssignCustomerToMonths/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignCustomerToMonth = await _context.AssignCustomerToMonths
                .Include(a => a.Customer)
                    .Include(a => a.Month)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (assignCustomerToMonth == null)
            {
                return NotFound();
            }

            return View(assignCustomerToMonth);
        }

        // POST: AssignCustomerToMonths/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var assignCustomerToMonth = await _context.AssignCustomerToMonths.FindAsync(id);
            _context.AssignCustomerToMonths.Remove(assignCustomerToMonth);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssignCustomerToMonthExists(int id)
        {
            return _context.AssignCustomerToMonths.Any(e => e.Id == id);
        }

        #endregion

    }
}

AssignToMonth/Views/AssignedCustomerToMonths/Create.cshtml
@model List<AssignCustomerToMonth>

@{
    ViewData["Title"] = "Planera kunder";
}

<div class="customer-top-bar">
    <i class="fas fa-user-tie"></i>
    <h1>Kund/Månadsplanering</h1>
</div>

<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm("Create", "AssignedCustomerToMonths", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div>
                <a href="#" id="addNew"><i class="fas fa-plus-square" style="color:green"></i></a>
            </div>

            <table id="dataTable" class="table">
                <tr>
                    <th>Kund</th>
                    <th>Månad</th>
                    <th>FTE</th>
                    <th></th>
                </tr>
                @if (Model != null && Model.Count > 0)
                {
                    int j = 0;
                    foreach (var i in Model)
                    {
                        <tr>
                            <td>
                                @Html.DropDownListFor(a => a[j].CustomerId, (SelectList)ViewBag.Customers, htmlAttributes: new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.DropDownListFor(a => a[j].MonthId, (SelectList)ViewBag.Months, htmlAttributes: new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a[j].FTE, new { @class = "form-control" })
                            </td>
                            <td>
                                @if (j < 1)
                                {
                                    <a href="#" class="remove"><i class="far fa-times-circle" style="color:red"></i></a>
                                }
                            </td>
                        </tr>
                        j++;
                    }
                }
            </table>
            <div class="mb-2" style="color:red">@ViewBag.Message</div>
            <input type="submit" class="btn btn-success" value="Spara" />
        }
        <div class="mt-2">
            <a asp-action="Index">Tillbaka</a>
        </div>
    </div>
</div>



@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            //1. Add new row
            $("#addNew").click(function (e) {
                e.preventDefault();
                var last = $('#dataTable>tbody>tr:last');
                if (last.length > 0) {
                    var name = last.children().find('input,select,a')[0].name;
                    var index = Number(name.replace(/[^0-9]/gi, '')) + 1;
                    var tr = ('<tr>' + last.html().replace(/[0-9]+__/gi, index + '__') + '</tr>').replace(/\[[0-9]+\]+[.]/gi, '[' + index + '].');
                    $('#dataTable tbody').append(tr);
                }
            });

            // 2. Remove
            $('body').on("click", "a.remove", function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });

        });
    </script>
}

AssignToMonth/Views/AssignedCustomerToMonths/Delete.cshtml
@model AssignToMonth.Models.AssignCustomerToMonth

@{
    ViewData["Title"] = "Delete";
}

<div class="customer-top-bar">
    <i class="fas fa-user-tie"></i>
    <h1>Kund/Månadsplanering</h1>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Month)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Month.DisplayMonth)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Ta bort" class="btn btn-danger" /> |
        <a asp-action="Index">Tillbaka</a>
    </form>
</div>

AssignToMonth/Views/AssignedCustomerToMonths/Index.cshtml
@model IPagedList<AssignCustomerToMonth>

@{
    ViewData["Title"] = "Planering kund";
}

<div class="customer-top-bar">
    <i class="fas fa-user-tie"></i>
    <h1>Kund/Månadsplanering</h1>
</div>

<a asp-action="Create">Planera ny månad</a>

<div class="col-2 p-0">
    @using (Html.BeginForm("Index", "AssignedCustomerToMonths", FormMethod.Get))
    {
        <span class="mr-1">År</span>@Html.DropDownList("year", new SelectList(ViewBag.Year), "Välj år", new { @class = "form-control" })
        <span class="mr-1">Månad</span>@Html.DropDownList("month", new SelectList(ViewBag.Month), "Välj månad", new { @class = "form-control" })
        <div id="customerBtn" class="d-flex justify-content-between">
            <input class="btn btn-dark mt-3 col-5" type="submit" value="Sök" />
            <a class="btn btn-dark mt-3 col-5" asp-action="Index">Rensa</a>
        </div>        
    }    
</div>

<table id="tblCustomers" class="table styled-table-customers mt-2">
    <thead>
        <tr>
            <td hidden>
                <span>Id</span>
            </td>
            <th>
                <span>Månad</span>
            </th>
            <th>
                <span>Kund</span>
            </th>
            <th>
                <span>FTE</span>
            </th>
            <th>
                <span>Timmar</span>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="Id" hidden>
                    <span>@Html.DisplayFor(modelItem => item.Id)</span>
                </td>
                <td class="Month">
                    <span>@Html.DisplayFor(modelItem => item.Month.DisplayMonth)</span>
                </td>
                <td class="Name">
                    <span>@Html.DisplayFor(modelItem => item.Customer.Name)</span>
                </td>
                <td class="FTE">
                    <span>@Html.DisplayFor(modelItem => item.FTE)</span>
                    <input type="text" min="0" step=".01" class="form-control-sm" value="@item.FTE" style="display:none" />
                </td>
                <td>
                    @item.FteToHours()
                </td>
                <td>
                    <a class="Edit" href="javascript:;">Editera</a>
                    <a class="Update" href="javascript:;" style="display:none">Uppdatera</a>
                    <a class="Cancel" href="javascript:;" style="display:none">Avbryt</a>
                    <a class="Delete" asp-action="Delete" asp-route-id="@item.Id">Ta bort</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="col-12 align-content-center">
    Sida @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) av @Model.PageCount
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page, currentYear = ViewBag.CurrentYear, currentMonth = ViewBag.CurrentMonth, }), new X.PagedList.Web.Common.PagedListRenderOptions
    {
        ContainerDivClasses = new[] { "navigation" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
    })
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>
    <script type="text/javascript">
        //Edit
        $("body").on("click", "#tblCustomers .Edit", function () {
            var row = $(this).closest("tr");
            $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    $(this).find("input").show();
                    $(this).find("span").hide();
                }
            });
            row.find(".Update").show();
            row.find(".Cancel").show();
            row.find(".Delete").hide();
            $(this).hide();
        });

        //Update
        $("body").on("click", "#tblCustomers .Update", function () {
            var row = $(this).closest("tr");
            $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    var span = $(this).find("span");
                    var input = $(this).find("input");
                    span.html(input.val());
                    span.show();
                    input.hide();
                }
            });
            row.find(".Edit").show();
            row.find(".Delete").show();
            row.find(".Cancel").hide();
            $(this).hide(); 

            var _customer = {
                Id: row.find(".Id").find("span").text(),
                Month:row.find(".Month").find("span").text(),
                Name: row.find(".Name").find("span").text(),
                FTE: row.find(".FTE").find("span").text(), 
            }
            $.ajax({
                type: "POST",
                url: "/AssignedCustomerToMonths/UpdateCustomer",
                data: _customer,
                dataType: "json",                
            });
            console.log(_customer)
        });

        //Cancel
        $("body").on("click", "#tblCustomers .Cancel", function () {
            var row = $(this).closest("tr");
            $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    var span = $(this).find("span");
                    var input = $(this).find("input");
                    input.val(span.html());
                    span.show();
                    input.hide();
                }
            });
            row.find(".Edit").show();
            row.find(".Delete").show();
            row.find(".Update").hide();
            $(this).hide();
        });
    </script>
}