AssignToMonth/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssignToMonth.Data;
using AssignToMonth.Models;

namespace AssignToMonth.Controllers
{
    public class CustomersController : Controller
    {
        private readonly SqlDbContext _context;

        public CustomersController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.ToListAsync());
        }

        #region CREATE METHOD

        // GET: Customers/Create
        public IActionResult Create()
        {
            List<Customer> customers = new List<Customer> { new Customer { Id = 0, Name = "" } };
            return View(customers);
        }


        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(List<Customer> customers)
        {
            if (ModelState.IsValid)
            {
                foreach (var customer in customers)
                {
                    _context.Customers.Add(customer);
                    await _context.SaveChangesAsync();

                    foreach (var month in _context.Months)
                    {
                        AssignCustomerToMonth model = new AssignCustomerToMonth();
                        model.CustomerId = customer.Id;
                        for (int i = 0; i < month.Id; i++)
                        {
                            model.MonthId = month.Id;
                        }
                        model.FTE = 0;
                        _context.AssignCustomerToMonths.Add(model);
                    }
                }
                await _context.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            return View(customers);
        }

        #endregion

        #region EDIT METHOD
        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        #endregion

        #region DELETE METHOD

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }

        #endregion
    }
}

AssignToMonth/Controllers/DashboardController.cs
using AssignToMonth.Data;
using AssignToMonth.Models;
using AssignToMonth.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace AssignToMonth.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ILogger<DashboardController> _logger;
        private readonly SqlDbContext _context;

        public DashboardController(ILogger<DashboardController> logger, SqlDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(int? year, string month, int? page, int currentYear, string currentMonth)
        {
            ViewBag.Year = (from item in _context.Months
                            select item.Year).Distinct();
            ViewBag.Month = (from item in _context.Months
                             select item.MonthName).Distinct();

            if (year != null || month != null)
            {
                page = 1;
            }
            else
            {
                year = currentYear;
                month = currentMonth;
            }

            ViewBag.CurrentYear = year;
            ViewBag.CurrentMonth = month;

            int pageSize = 12;
            int pageNumber = (page ?? 1);

            var dashBoard = new DashboardViewModel()
            {
                Users = _context.Users.ToList(),
                Customers = _context.Customers.ToList(),
                Months = _context.Months.ToList(),
                AssignedCustomerToMonths = (from item in _context.AssignCustomerToMonths
                                           orderby item.Month.Id ascending
                                           where item.Month.Year == year || year == null || year == 0
                                           where item.Month.MonthName == month || month == null || month == ""
                                           select item).ToPagedList(pageNumber, pageSize),

                AssignedUsersToMonths = (from item in _context.AssignedMonths.Include(m => m.AllocateTimes)
                                        orderby item.Month.Id ascending
                                        where item.Month.Year == year || year == null || year == 0
                                        where item.Month.MonthName == month || month == null || month == ""
                                        select item).ToPagedList(pageNumber, pageSize),            
            };                         
            return View(dashBoard);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AssignToMonth/Controllers/MonthsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssignToMonth.Data;
using AssignToMonth.Models;

namespace AssignToMonth.Controllers
{
    public class MonthsController : Controller
    {
        private readonly SqlDbContext _context;

        public MonthsController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: Months
        public IActionResult Index(int? year)
        {
            ViewBag.Year = (from m in _context.Months
                            select m.Year).Distinct();

            var model = from m in _context.Months
                        orderby m.Year
                        where m.Year == year || year == null || year == 0
                        select m;
            return View(model);
        }

        #region CREATE METHOD
        // GET: Months/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Months/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MonthName,Year,Hours")] Month month)
        {
            if (ModelState.IsValid)
            {
                _context.Add(month);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(month);
        }

        #endregion

        #region EDIT METHOD
        // GET: Months/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var month = await _context.Months.FindAsync(id);
            if (month == null)
            {
                return NotFound();
            }
            return View(month);
        }

        // POST: Months/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MonthName,Year,Hours")] Month month)
        {
            if (id != month.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(month);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MonthExists(month.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(month);
        }

        #endregion

        #region DELETE METHOD
        // GET: Months/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var month = await _context.Months
                .FirstOrDefaultAsync(m => m.Id == id);
            if (month == null)
            {
                return NotFound();
            }

            return View(month);
        }

        // POST: Months/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var month = await _context.Months.FindAsync(id);
            _context.Months.Remove(month);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        private bool MonthExists(int id)
        {
            return _context.Months.Any(e => e.Id == id);
        }
    }
}

AssignToMonth/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssignToMonth.Data;
using AssignToMonth.Models;

namespace AssignToMonth.Controllers
{
    public class UsersController : Controller
    {
        private readonly SqlDbContext _context;

        public UsersController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public IActionResult Index()
        {
            var usersToEdit = from item in _context.Users
                              orderby item.Id
                              select item;         

            return View(usersToEdit.ToList());            
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            List<User> user = new List<User> { new User { Id = 0, FirstName = "", LastName = "" } };
            return View(user);
        }

        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(List<User> users)
        {
            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    _context.Users.Add(user);
                    await _context.SaveChangesAsync();

                    foreach (var month in _context.Months)
                    {
                        AssignedMonth model = new AssignedMonth();
                        model.UserId = user.Id;
                        for (int i = 0; i < month.Id; i++)
                        {
                            model.MonthId = month.Id;
                        }
                        model.Absence = 0;
                        _context.AssignedMonths.Add(model);
                    }
                }
                await _context.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateUser(User user)
        {
            User updatedUser = (from u in _context.Users
                                where u.Id == user.Id
                                select u).FirstOrDefault();

            updatedUser.FirstName = user.FirstName;
            updatedUser.LastName = user.LastName;
            await _context.SaveChangesAsync();

            return new EmptyResult();
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

AssignToMonth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssignToMonth</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/usertopbar.css" />
    <link rel="stylesheet" href="~/css/customertopbar.css" />
    <link rel="stylesheet" href="~/css/plannertopbar.css" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/043e51ac62.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <partial name="_NavbarPartial" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a>&copy; 2021 - Knowit </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AssignToMonth/Views/Shared/_NavbarPartial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index"><img src="~/images/logotype.svg" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Översikt</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Team
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Översikt</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="AssignedUserToMonths" asp-action="Index">Månadsplanering</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Kunder
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Översikt</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="AssignedCustomerToMonths" asp-action="Index">Månadsplanering</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="AllocateTimes" asp-action="Index">Planering</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Months" asp-action="Index">Månader</a>
                </li>

            </ul>
        </div>
    </div>
</nav>

AssignToMonth/Views/Shared/_customerCardPartial.cshtml
@model IEnumerable<Customer>
<link rel="stylesheet" href="~/css/customercard.css" />

<div class="row">
    @foreach (var customer in Model)
    {
        <div class="col-md-4">
            <div class="customer-card customer">
                <div class="d-flex justify-content-between">
                    <i class="fas fa-user-tie"></i>
                    <div>
                        <span class="customer-name">@customer.Name</span>
                    </div>
                </div>
                <div class="customer-panel">
                    <a asp-action="Edit" asp-route-id="@customer.Id">Editera</a> |
                    <a asp-action="Delete" asp-route-id="@customer.Id">Ta bort</a>
                </div>
            </div>
        </div>
    }
</div>

AssignToMonth/Views/Shared/_userCardPartial.cshtml
@model IEnumerable<User>
<link rel="stylesheet" href="~/css/usercard.css" />

<div class="row">
    @foreach (var user in Model)
    {
        <div class="col-md-4">
            <div class="user-card user">
                <div class="d-flex justify-content-between">
                    <i class="fa fa-users"></i>
                    <div>
                        <span class="user-firstname">@user.FirstName</span>
                        <span class="user-lastname">@user.LastName</span>
                    </div>
                </div>
                <div class="user-panel">
                    <a asp-action="Edit" asp-route-id="@user.Id">Editera</a> |
                    <a asp-action="Delete" asp-route-id="@user.Id">Ta bort</a>
                </div>
            </div>
        </div>
    }
</div>