AssignToMonth/Controllers/AssignedUserToMonthsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssignToMonth.Data;
using AssignToMonth.Models;
using X.PagedList;

namespace AssignToMonth.Controllers
{
    public class AssignedUserToMonthsController : Controller
    {
        private readonly SqlDbContext _context;

        public AssignedUserToMonthsController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: AssignedMonths
        public IActionResult Index(int? year, string month, string user, int? page, string currentUser, int currentYear, string currentMonth)
        {
            ViewBag.Year = (from item in _context.Months
                            select item.Year).Distinct();
            ViewBag.Month = (from item in _context.Months
                            select item.MonthName).Distinct();
            ViewBag.Users = (from item in _context.Users
                             select item.FirstName).Distinct();

            if (year != null || month != null || user != null )
            {
                page = 1;
            }
            else
            {
                year = currentYear;
                user = currentUser;
                month = currentMonth;                
            }

            ViewBag.CurrentUser = user;
            ViewBag.CurrentYear = year;
            ViewBag.CurrentMonth = month;

            var pageNumber = page ?? 1;
            int pageSize = 12;

            var model = from item in _context.AssignedMonths
                            .Include(a => a.Month)
                                .Include(a => a.User)
                        orderby item.Month.Id
                        where item.Month.Year == year || year == null || year == 0
                        where item.Month.MonthName == month || month == null || month ==""
                        where item.User.FirstName == user || user == null || user == ""
                        select item;

            return View(model.ToPagedList(pageNumber, pageSize));
        }

        #region CREATE METHOD

        // GET: AssignedMonths/Create
        public IActionResult Create()
        {
            ViewBag.Users = new SelectList(_context.Users, "Id", "DisplayName");
            ViewBag.Months = new SelectList(_context.Months, "Id", "DisplayMonth");

            List<AssignedMonth> assignedUsers = new List<AssignedMonth> { new AssignedMonth { Id = 0, MonthId = 0, UserId = 0, Absence = 0 } };
            return View(assignedUsers);
        }

        // POST: AssignedMonths/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(List<AssignedMonth> assignedUsers)
        {
            ViewBag.Users = new SelectList(_context.Users, "Id", "DisplayName");
            ViewBag.Months = new SelectList(_context.Months, "Id", "DisplayMonth");

            if (ModelState.IsValid)
            {
                foreach (var user in assignedUsers)
                {
                    _context.AssignedMonths.Add(user);
                    //if (!_context.AssignedMonths.Any(c => c.MonthId.Equals(user.MonthId)))
                    //{
                    //    _context.AssignedMonths.Add(user);
                    //    await _context.SaveChangesAsync();
                    //    ModelState.Clear();
                    //    return RedirectToAction(nameof(Index));
                    //}
                    //else
                    //{
                    //    ViewBag.Message = "En person är redan planerad på denna månad";
                    //}
                }
                await _context.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            return View(assignedUsers);
        }
        #endregion

        #region EDIT METHOD
        [HttpPost]
        public async Task<IActionResult> UpdateUser(AssignedMonth _user)
        {
            var updatedUser = await _context.AssignedMonths.Where(x => x.Id == _user.Id).SingleOrDefaultAsync();

            if (updatedUser != null)
            {
                updatedUser.Absence = _user.Absence;
                await _context.SaveChangesAsync();
            }
            return new EmptyResult();
        }
        #endregion

        #region DELETE METHOD
        // GET: AssignedMonths/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignedMonth = await _context.AssignedMonths
                .Include(a => a.Month)
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (assignedMonth == null)
            {
                return NotFound();
            }

            return View(assignedMonth);
        }

        // POST: AssignedMonths/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var assignedMonth = await _context.AssignedMonths.FindAsync(id);
            _context.AssignedMonths.Remove(assignedMonth);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssignedMonthExists(int id)
        {
            return _context.AssignedMonths.Any(e => e.Id == id);
        }
    }
    #endregion
}

AssignToMonth/Views/AssignedUserToMonths/Create.cshtml
@model List<AssignedMonth>

@{
    ViewData["Title"] = "Planera användare";
}

<div class="user-top-bar">
    <i class="fa fa-users"></i>
    <h1>Team/Månadsplanering</h1>
</div>

<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm("Create", "AssignedUserToMonths", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div>
                <a href="#" id="addNew"><i class="fas fa-plus-square" style="color:green"></i></a>
            </div>

            <table id="dataTable" class="table">
                <tr>
                    <th>Användare</th>
                    <th>Månad</th>
                    <th>Frånvaro</th>
                    <th></th>
                </tr>
                @if (Model != null && Model.Count > 0)
                {
                    int j = 0;
                    foreach (var i in Model)
                    {
                        <tr>
                            <td>
                                @Html.DropDownListFor(a => a[j].UserId, (SelectList)ViewBag.Users, htmlAttributes: new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.DropDownListFor(a => a[j].MonthId, (SelectList)ViewBag.Months, htmlAttributes: new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a[j].Absence, new { @class = "form-control" })
                            </td>
                            <td>
                                @if (j < 1)
                                {
                                    <a href="#" class="remove"><i class="far fa-times-circle" style="color:red"></i></a>
                                }
                            </td>
                        </tr>
                        j++;
                    }
                }
            </table>
            <div class="mb-2" style="color:red">@ViewBag.Message</div>
            <input type="submit" class="btn btn-success" value="Spara" />
        }
        <div class="mt-2">
            <a asp-action="Index">Tillbaka</a>
        </div>
    </div>
</div>



@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            //1. Add new row
            $("#addNew").click(function (e) {
                e.preventDefault();
                var last = $('#dataTable>tbody>tr:last');
                if (last.length > 0) {
                    var name = last.children().find('input,select,a')[0].name;
                    var index = Number(name.replace(/[^0-9]/gi, '')) + 1;
                    var tr = ('<tr>' + last.html().replace(/[0-9]+__/gi, index + '__') + '</tr>').replace(/\[[0-9]+\]+[.]/gi, '[' + index + '].');
                    $('#dataTable tbody').append(tr);
                }
            });

            // 2. Remove
            $('body').on("click", "a.remove", function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });

        });
    </script>
}

AssignToMonth/Views/AssignedUserToMonths/Delete.cshtml
@model AssignToMonth.Models.AssignedMonth

@{
    ViewData["Title"] = "Delete";
}

<div class="user-top-bar">
    <i class="fa fa-users"></i>
    <h1>Team/Månadsplanering</h1>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Absence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Absence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.DisplayName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Month)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Month.DisplayMonth)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Ta bort" class="btn btn-danger" /> |
        <a asp-action="Index">Tillbaka</a>
    </form>
</div>

AssignToMonth/Views/AssignedUserToMonths/Index.cshtml
@model IPagedList<AssignToMonth.Models.AssignedMonth>

@{
    ViewData["Title"] = "Planering team";
}

<div class="user-top-bar">
    <i class="fa fa-users"></i>
    <h1>Team/Månadsplanering</h1>
</div>

<p>
    <a asp-action="Create">Planera ny månad</a>
</p>

<p>
    <div class="col-2 p-0">
        @using (Html.BeginForm("Index", "AssignedUserToMonths", FormMethod.Get))
        {
            <span>År</span>@Html.DropDownList("year", new SelectList(ViewBag.Year), "Välj år", new { @class = "form-control" })
            <span>Månad</span>@Html.DropDownList("month", new SelectList(ViewBag.Month), "Välj månad", new { @class = "form-control" })
            <span>Användare</span>@Html.DropDownList("user", new SelectList(ViewBag.Users), "Välj användare", new { @class = "form-control" })            
            <div id="userBtn" class="d-flex justify-content-between">
                <input class="btn btn-dark mt-3 col-5" type="submit" value="Sök" />
                <a class="btn btn-dark mt-3 col-5" asp-action="Index">Rensa</a>
            </div>
        }
    </div>
</p>
<table id="tblUsers" class="table styled-table-users mt-2">
    <thead>
        <tr>
            <th hidden>
                <span>År</span>
            </th>
            <th>
                <span>Månad</span>
            </th>
            <th>
                <span>Användare</span>
            </th>
            <th>
                <span>Timmar</span>
            </th>
            <th>
                <span>Frånvaro</span>
            </th>
            <th>
                <span>Totala timmar</span>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="Id" hidden>
                    <span>@item.Id</span>
                </td>
                <td class="Month">
                    <span>@Html.DisplayFor(modelItem => item.Month.DisplayMonth)</span>
                </td>
                <td class="Name">
                    <span>@Html.DisplayFor(modelItem => item.User.DisplayName)</span>
                </td>
                <td class="WorkHours">
                    <span>@Html.DisplayFor(modelItem => item.Month.Hours)</span>
                </td>
                <td class="Absence">
                    <span>@Html.DisplayFor(modelItem => item.Absence)</span>
                    <input type="number" class="form-control-sm" value="@item.Absence" style="display:none" />
                </td>
                <td>
                    @String.Format(("{0:n0}"), item.TotalHours())
                </td>
                <td>
                    <a class="Edit" href="javascript:;">Editera |</a>
                    <a class="Update" href="javascript:;" style="display:none">Uppdatera |</a>
                    <a class="Cancel" href="javascript:;" style="display:none">Avbryt</a>
                    <a class="Delete" asp-action="Delete" asp-route-id="@item.Id">Ta bort</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<div class="col-12 align-content-center">
    Sida @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) av @Model.PageCount
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page, currentUser = ViewBag.CurrentUser, currentYear = ViewBag.CurrentYear, currentMonth = ViewBag.CurrentMonth, }), new X.PagedList.Web.Common.PagedListRenderOptions
    {
        ContainerDivClasses = new[] { "navigation" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
    })
</div>



@section Scripts {
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>
    <script type="text/javascript">
        //Edit
        $("body").on("click", "#tblUsers .Edit", function () {
            var row = $(this).closest("tr");
            $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    $(this).find("input").show();
                    $(this).find("span").hide();
                }
            });
            row.find(".Update").show();
            row.find(".Cancel").show();
            row.find(".Delete").hide();
            $(this).hide();
        });

        //Update
        $("body").on("click", "#tblUsers .Update", function () {
            var row = $(this).closest("tr");
            $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    var span = $(this).find("span");
                    var input = $(this).find("input");
                    span.html(input.val());
                    span.show();
                    input.hide();
                }
            });
            row.find(".Edit").show();
            row.find(".Delete").show();
            row.find(".Cancel").hide();
            $(this).hide();

            var _user = {
                Id: row.find(".Id").find("span").text(),
                Month: row.find(".Month").find("span").text(),
                Name: row.find(".Name").find("span").text(),
                WorkHours: row.find(".WorkHours").find("span").text(),
                Absence: row.find(".Absence").find("span").text(), 
            }
            $.ajax({
                type: "POST",
                url: "/AssignedUserToMonths/UpdateUser",
                data: _user,
                dataType: "json"
            });
            console.log(_user)
        });

        //Cancel
        $("body").on("click", "#tblUsers .Cancel", function () {
            var row = $(this).closest("tr");
            $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    var span = $(this).find("span");
                    var input = $(this).find("input");
                    input.val(span.html());
                    span.show();
                    input.hide();
                }
            });
            row.find(".Edit").show();
            row.find(".Delete").show();
            row.find(".Update").hide();
            $(this).hide();
        });
    </script>
}